---
name: mhae-jit

# Example workflow for self-hosted runners
on:
  # Runs when triggered manually via GitHub Actions page
  workflow_dispatch:
    inputs:
      # Can use specific Gerrit refspec, otherwise pull latest SPDK master
      gerrit_ref:
        description: 'Gerrit refspec to test following refs/changes/XX/YYYYY/Z format'
        required: false
        type: string
        default: ''

jobs:
  mhae-jit:
    runs-on: [jit-test]
    env:
      gerrit_ref: ${{ inputs.gerrit_ref }}
      spdk_path: './spdk'
    steps:
      # Required to use locally defined actions
    - name: Checkout the spdk-ci repo locally
      uses: actions/checkout@v4
    - name: Checkout SPDK repo from Gerrit
      uses: ./.github/actions/checkout_gerrit
      with:
        gerrit_ref: ${{ env.gerrit_ref }}
        spdk_path: ${{ env.spdk_path }}
    - name: autorun-nvmf
      run: |
        cd spdk
        mkdir -p ./output/unittest
        cat > funtest.conf << EOF
        SPDK_RUN_FUNCTIONAL_TEST=1
        SPDK_TEST_UNITTEST=0
        SPDK_TEST_NVMF=1
        SPDK_TEST_NVMF_TRANSPORT="rdma"
        HUGEMEM=2048
        # Set up the DEPENDENCY_DIR
        DEPENDENCY_DIR=/home/vagrant
        EOF
        # SRIOV hack (but does not work with in-box driver)
        sed -i 's/0xa2d6/0x101e/g' test/nvmf/common.sh
        ./autorun.sh ./funtest.conf
